### ISSUE TITLE
Check to see if ios is using assets catalog

### ISSUE THREAD

**Issue by mhartington** [AlexDisler/cordova-icon#5] opened 2014-05-23 14:27 UTC
First off, loving the script, a big life saver for cordova apps. Not sure if this would be possible, but it would be great if you could updates the icons for ios in the assets catalog.

**Comment by devgeeks** [comment] 2015-04-10 00:50
:+1:

**Comment by grahovam** [comment] 2015-11-12 17:56
+1

**Comment by devgeeks** [comment] 2015-11-12 20:20
@AlexDisler at it's heart, this is really not much more than a destination location change.

**Comment by Kingside** [comment] 2015-12-17 20:59
I don't think that this should be a "check", asset catalogs have long been the standard for some time now, I think this plugin simply needs to be updated with a full migration to using asset catalogs instead.

@AlexDisler, @devgeeks really isn't exaggerating. An asset catalog is just a folder of images. Past that, there's simply a master `contents.json` file that sits next to the images in the folder, which holds a collection of objects, 1 for each icon size. The keys in each object are simply strings. One key tells Xcode which icon variant an image represents, and another tells Xcode the exact file name of the icon inside of the asset catalog folder, mapping the correct association. So aside from the location change that @devgeeks mentioned, once this json file has been created, it can just be commited since the hook scripts won't have any need to modify it.

I believe Xcode even has a feature if you look at your build settings, where there's a button next to application icons still using the old method that reads something like "convert to asset catalog" that will do all the heavy lifting for you. If you run any already existing application through that tool, and do nothing else, it should leave you with a very helpful and clear git diff, showing you how that json needs to be formatted.

If you'd like any help in understanding or implementing asset catalogs, I'd be happy to help walk you through anything you like.

I think your plugin is really great, and would definitely remove several extra and redundant steps in our process with apps that I work on. We've already moved on to adopting asset catalogs though, so this plugin isn't something we could install until it has support for them.

I'm off work through Christmas, let me know if I can be of any help!

**Comment by devgeeks** [comment] 2015-12-18 02:40
cordova-ios@4.x (out now) uses asset catalogs as well. So, it is certainly the "future"

**Comment by BrunoCartier** [comment] 2016-03-08 23:11
Closing this since last versions have the good and updated icon path for iOS. Please re-open if my understanding of the issue is wrong.

**Closed by BrunoCartier** 2016-03-08 23:11 UTC
Labels: enhancement, help wanted
